In [1]:
import torch as t
from torch.autograd import Variable

In [2]:
x = Variable(t.ones(2,2),requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x.sum()
print(y)

tensor(4., grad_fn=<SumBackward0>)


In [4]:
y.grad_fn

In [5]:
y.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [6]:
#grad在反向传播过程中会累加
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [7]:
# 梯度归零
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [8]:
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [9]:
x = Variable(t.ones(4,5))
y = t.cos(x)
x_tenbsor_cos = t.cos(x.data)
print(y)
print(x_tenbsor_cos)

tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])
tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])
