In [1]:
import torch as t

#### Tensor

In [2]:
a = t.Tensor(5,5)
print(a)
print(a.shape)

tensor([[0.0000e+00, 0.0000e+00, 1.8788e+31, 1.7220e+22, 1.5471e-04],
        [1.0532e+21, 1.0244e-11, 1.0571e+21, 8.1345e+20, 2.1177e-07],
        [1.6502e-07, 1.3120e-08, 2.7450e-06, 3.1369e+27, 7.0800e+31],
        [3.1095e-18, 1.8590e+34, 7.7767e+31, 1.8056e+28, 3.3130e-18],
        [1.9421e+31, 2.7491e+20, 6.1949e-04, 8.8916e-10, 1.0314e-08]])
torch.Size([5, 5])


In [3]:
c = t.Tensor(10000,10000)
print(c)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [4]:
#构建一个随机初始化的tensor
x = t.rand(5,3)
print(x)
print(x.shape)

tensor([[0.1496, 0.7927, 0.8189],
        [0.6862, 0.9032, 0.4650],
        [0.6812, 0.0977, 0.3031],
        [0.4871, 0.3877, 0.4988],
        [0.3585, 0.6131, 0.6071]])
torch.Size([5, 3])


In [5]:
y = t.rand(5,3)
print(y)
print(y.shape)

tensor([[0.8600, 0.4431, 0.4064],
        [0.3098, 0.1482, 0.2548],
        [0.1918, 0.8892, 0.2462],
        [0.6830, 0.7861, 0.7376],
        [0.7678, 0.3821, 0.6258]])
torch.Size([5, 3])


#### tensor加法

In [6]:
#加法1
x + y

tensor([[1.0097, 1.2359, 1.2253],
        [0.9960, 1.0514, 0.7198],
        [0.8729, 0.9869, 0.5493],
        [1.1701, 1.1738, 1.2364],
        [1.1263, 0.9952, 1.2329]])

In [7]:
#加法2
t.add(x,y)

tensor([[1.0097, 1.2359, 1.2253],
        [0.9960, 1.0514, 0.7198],
        [0.8729, 0.9869, 0.5493],
        [1.1701, 1.1738, 1.2364],
        [1.1263, 0.9952, 1.2329]])

In [8]:
#加法3，指定结果的输出目标为resut
result = t.Tensor(5,3)
t.add(x,y,out = result)
print(result)

tensor([[1.0097, 1.2359, 1.2253],
        [0.9960, 1.0514, 0.7198],
        [0.8729, 0.9869, 0.5493],
        [1.1701, 1.1738, 1.2364],
        [1.1263, 0.9952, 1.2329]])


#### 结果保存

In [9]:
#不改变值
print('最初的y:')
print(y)
y.add(x)
print('加法后的y:')
print(y)

最初的y:
tensor([[0.8600, 0.4431, 0.4064],
        [0.3098, 0.1482, 0.2548],
        [0.1918, 0.8892, 0.2462],
        [0.6830, 0.7861, 0.7376],
        [0.7678, 0.3821, 0.6258]])
加法后的y:
tensor([[0.8600, 0.4431, 0.4064],
        [0.3098, 0.1482, 0.2548],
        [0.1918, 0.8892, 0.2462],
        [0.6830, 0.7861, 0.7376],
        [0.7678, 0.3821, 0.6258]])


In [10]:
#加了_后改变值
print('最初的y:')
print(y)
y.add_(x)
print('加法后的y:')
print(y)

最初的y:
tensor([[0.8600, 0.4431, 0.4064],
        [0.3098, 0.1482, 0.2548],
        [0.1918, 0.8892, 0.2462],
        [0.6830, 0.7861, 0.7376],
        [0.7678, 0.3821, 0.6258]])
加法后的y:
tensor([[1.0097, 1.2359, 1.2253],
        [0.9960, 1.0514, 0.7198],
        [0.8729, 0.9869, 0.5493],
        [1.1701, 1.1738, 1.2364],
        [1.1263, 0.9952, 1.2329]])


#### tensor  与   numpy

In [11]:
# tensor  >>>  numpy
a = t.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [12]:
# numpy  >>>  tensor
c = t.from_numpy(b)
print(c)


tensor([1., 1., 1., 1., 1.])
