#### 基本操作

In [1]:
import torch as t

In [2]:
#指定形状的tensor
a = t.Tensor(2,3)
print(a)

tensor([[2.5676e+12, 9.3186e-43, 2.2260e+12],
        [9.3186e-43, 2.3424e+12, 9.3186e-43]])


In [3]:
#用list的数据创建tensor
b = t.Tensor([[1,2,3],[4,5,6]])
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
#将tensor转list
b.tolist()


[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [5]:
#.size()
b_size = b.size()
print(b_size)

torch.Size([2, 3])


In [6]:
#返回元素的个数
b.numel()

6

In [7]:
#创建一个和b相同形状的tensor
c = t.Tensor(b.size())
#创建一个元素为2，3的tensor
d = t.Tensor((2,3))
c,d

(tensor([[2.5606e+12, 9.3186e-43, 2.3425e+12],
         [9.3186e-43, 2.3424e+12, 9.3186e-43]]), tensor([2., 3.]))

In [8]:
#tensor.shape等价于tensor.size()
print(c.shape)
print(d.size())


torch.Size([2, 3])
torch.Size([2])


In [9]:
#各种生成Tensor的方式
print(t.ones(2,3))
print(t.zeros(2,3))
print(t.arange(1,6,2))
print(t.linspace(1,10,3))
print(t.randn(2,3))
print(t.rand(2,3))
print(t.randperm(5))#长度为5的随机排列
print(t.eye(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1, 3, 5])
tensor([ 1.0000,  5.5000, 10.0000])
tensor([[ 0.9295, -2.1394, -0.9394],
        [ 0.1979, -0.5792, -1.4111]])
tensor([[0.7593, 0.2021, 0.7774],
        [0.3020, 0.1510, 0.7589]])
tensor([4, 2, 1, 3, 0])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


#### 常见的tensor操作 view  unsqueeze    squeeze   resize

In [10]:
a = t.arange(0,6)
#view修改形状
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [11]:
b = a.view(-1,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [12]:
print(b.unsqueeze(1))
print(b.unsqueeze(1).shape)  #在第1维上增加1

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])
torch.Size([2, 1, 3])


In [13]:
print(b.unsqueeze(-2))
print(b.unsqueeze(-2).shape)  #在第-2维上增加1

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])
torch.Size([2, 1, 3])


In [14]:
c = b.view(1,1,1,2,3)
print(c.shape)
c.squeeze(0)
print(c.squeeze(0).shape)#压缩第0维的1

torch.Size([1, 1, 1, 2, 3])
torch.Size([1, 1, 2, 3])


In [15]:
c.squeeze()#把所有维度的1压缩

tensor([[0, 1, 2],
        [3, 4, 5]])

In [16]:
#resize
b.resize_(1,3)
b

tensor([[0, 1, 2]])

In [17]:
b.resize_(3,3)
b

tensor([[                  0,                   1,                   2],
        [                  3,                   4,                   5],
        [      2857564116952,       2857905433096, 2308767710143578117]])

#### 索引操作

In [29]:
a = t.randn(3,4)
a

tensor([[ 1.7743, -0.7880, -1.4763,  0.2253],
        [ 0.6323,  0.0298,  0.4733, -2.1163],
        [ 0.0680, -0.3000,  0.3964,  2.7610]])

In [19]:
a[0]

tensor([-0.7318, -0.3810, -1.4540, -1.1067])

In [20]:
a[:,0]

tensor([-0.7318,  0.5135,  1.2747])

In [26]:
a[1,2]

tensor(-1.5944)

In [27]:
a[:2,0:2]

tensor([[-0.7318, -0.3810],
        [ 0.5135,  0.6855]])

In [31]:
a>0

tensor([[1, 0, 0, 1],
        [1, 1, 1, 0],
        [1, 0, 1, 1]], dtype=torch.uint8)

In [32]:
a[a>0]

tensor([1.7743, 0.2253, 0.6323, 0.0298, 0.4733, 0.0680, 0.3964, 2.7610])

In [35]:
a[t.LongTensor([0,1])]

tensor([[ 1.7743, -0.7880, -1.4763,  0.2253],
        [ 0.6323,  0.0298,  0.4733, -2.1163]])