#### Tensor类型

In [1]:
import torch as t


In [2]:
#设置默认tensor

a = t.Tensor(2,3)
print(a.dtype)
a

torch.float32


tensor([[2.1256e-30, 5.8855e-43, 1.4025e-30],
        [5.8855e-43, 1.4443e-30, 5.8855e-43]])

In [3]:
b = a.float()
#与下面一行等价
b = a.type(t.FloatTensor)
b

tensor([[2.1256e-30, 5.8855e-43, 1.4025e-30],
        [5.8855e-43, 1.4443e-30, 5.8855e-43]])

In [4]:
c = a.type_as(b)
c


tensor([[2.1256e-30, 5.8855e-43, 1.4025e-30],
        [5.8855e-43, 1.4443e-30, 5.8855e-43]])

In [5]:
d = a.new(2,3)
d

tensor([[3.8686e+25, 9.1836e-39, 1.2771e-40],
        [9.0079e+15, 1.6751e-37, 2.9775e-41]])

#### 逐元素操作

In [6]:
a = t.arange(0.,6.).view(2,3)
t.cos(a)

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837]])

In [7]:
print(a%3) #求余，两行代码效果一致
print(t.fmod(a,3))

tensor([[0., 1., 2.],
        [0., 1., 2.]])
tensor([[0., 1., 2.],
        [0., 1., 2.]])


In [8]:
t.pow(a,2)

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [9]:
print(t.clamp(a,min = 3)) #每个元素与3比较

tensor([[3., 3., 3.],
        [3., 4., 5.]])


#### 归并操作

In [10]:
#sum
b = t.ones(2,3)
print(b.sum(dim = 0 ,keepdim = True))


tensor([[2., 2., 2.]])


In [11]:
print(b.sum(dim = 1))

tensor([3., 3.])


In [12]:
a = t.arange(0,6).view(2,3)
print(a)
print(a.cumsum(dim = 1)) #按行累加


tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 0,  1,  3],
        [ 3,  7, 12]])


#### 比较

In [13]:
a = t.linspace(0,15,6).view(2,3)
a

tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]])

In [14]:
b = t.linspace(15,0,6).view(2,3)
b


tensor([[15., 12.,  9.],
        [ 6.,  3.,  0.]])

In [15]:
a>b

tensor([[0, 0, 0],
        [1, 1, 1]], dtype=torch.uint8)

In [16]:
a[a>b] #选出a>b的元素

tensor([ 9., 12., 15.])

In [17]:
t.max(a)

tensor(15.)

In [18]:
t.max(a,b) #选a,b中较大的

tensor([[15., 12.,  9.],
        [ 9., 12., 15.]])

In [19]:
t.clamp(a,10) #选a和10较大的

tensor([[10., 10., 10.],
        [10., 12., 15.]])

#### Tensor和Numpy

In [20]:
import numpy as np
a = np.ones([2,3],dtype = np.float32)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [21]:
b = t.from_numpy(a) #numpy转Tensor
print(b)
b = t.Tensor(a) #也可以直接生产一个tensor
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [22]:
b.numpy() #Tensor转numpy

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [23]:
a[0,1] = 100 #共享内存
b

tensor([[  1., 100.,   1.],
        [  1.,   1.,   1.]])

#### 向量化

In [24]:
def for_loop_add(x, y):
    result = []
    for i,j in zip(x, y):
        result.append(i + j)
    return t.Tensor(result)


In [25]:
x = t.zeros(100)
y = t.ones(100)
%timeit -n 10 for_loop_add(x, y)
%timeit -n 10 x + y

10 loops, best of 3: 994 µs per loop
10 loops, best of 3: 4.3 µs per loop
