In [1]:
import torch 
import numpy as np


#### numpy与torch 转换

In [2]:
np_data = np.arange(6).reshape((2,3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:', tensor2array, # [[0 1 2], [3 4 5]]
)


numpy array: [[0 1 2]
 [3 4 5]] 
torch tensor: tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
tensor to array: [[0 1 2]
 [3 4 5]]


In [3]:
#abs
data = [-1,-2,1,2]
tensor = torch.FloatTensor(data)

print(
'\nnumpy: ', np.abs(data),          # [1 2 1 2]
'\ntorch: ', torch.abs(tensor)      # [1 2 1 2]
)



numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])


In [4]:
# sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)


sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [5]:
# mean
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor)     # 0.0
)



mean 
numpy:  0.0 
torch:  tensor(0.)


In [6]:
# matrix multiplication
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)
# incorrect method
data = np.array(data)
print(
    '\nmatrix multiplication (dot)',
    '\nnumpy: ', data.dot(data),        # [[7, 10], [15, 22]]
    '\ntorch: ', tensor.dot(tensor)     # this will convert tensor to [1,2,3,4], you'll get 30.0
)



matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


RuntimeError: dot: Expected 1-D argument self, but got 2-D

In [7]:
np_a = np.arange(6).reshape((3,2))
tensor_a = torch.from_numpy(np_a)


In [8]:
np_a,tensor_a

(array([[0, 1],
        [2, 3],
        [4, 5]]), tensor([[0, 1],
         [2, 3],
         [4, 5]], dtype=torch.int32))

In [9]:
tensor_a.numpy()


array([[0, 1],
       [2, 3],
       [4, 5]])