In [1]:
import torch
from torch.autograd import Variable



In [2]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor,requires_grad = True)


In [3]:
tensor,variable

(tensor([[1., 2.],
         [3., 4.]]), tensor([[1., 2.],
         [3., 4.]], requires_grad=True))

In [4]:
t_out = torch.mean(tensor * tensor) # x^2
v_out = torch.mean(variable * variable) 
print(t_out)
print(v_out)


tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


In [5]:
v_out.backward()
# v_out = 1/4 * sum(variable*variable)
# the gradients w.r.t the variable, d(v_out)/d(variable) = 1/4*2*variable = variable/2
print(variable.grad)


tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [6]:
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])


In [7]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
