In [1]:
import torch
import torch.utils.data as Data


In [12]:
BATCG_SIZE = 6


In [13]:
x = torch.linspace(1,10,10)
y = torch.linspace(10,1,10)

torch_dataset = Data.TensorDataset(x, y)

loader = Data.DataLoader(
    dataset = torch_dataset,
    batch_size = BATCG_SIZE,
    shuffle=False,
    num_workers = 2
)

for epoch in range(3):
    for step,(batch_x,batch_y) in enumerate(loader):
        print(batch_x,batch_y)


tensor([1., 2., 3., 4., 5., 6.]) tensor([10.,  9.,  8.,  7.,  6.,  5.])
tensor([ 7.,  8.,  9., 10.]) tensor([4., 3., 2., 1.])
tensor([1., 2., 3., 4., 5., 6.]) tensor([10.,  9.,  8.,  7.,  6.,  5.])
tensor([ 7.,  8.,  9., 10.]) tensor([4., 3., 2., 1.])
tensor([1., 2., 3., 4., 5., 6.]) tensor([10.,  9.,  8.,  7.,  6.,  5.])
tensor([ 7.,  8.,  9., 10.]) tensor([4., 3., 2., 1.])
