## 3.2.1 Variable  

In [1]:
import torch as t
from torch.autograd import Variable as V


In [2]:
a = V(t.ones(3,4),requires_grad = True)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [3]:
b = V(t.zeros(3,4))
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
c = a.add(b)
c


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], grad_fn=<AddBackward0>)

In [5]:
d = c.sum()
d.backward()

In [6]:
#前者取了data后为tensor,后者为variable
c.data.sum(),c.sum()

(tensor(12.), tensor(12., grad_fn=<SumBackward0>))

In [7]:
a.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
a.requires_grad,b.requires_grad,c.requires_grad

(True, False, True)

In [9]:
#由用户创建的variable为叶子节点
a.is_leaf,b.is_leaf,c.is_leaf

(True, True, False)

In [10]:
#c不是叶子节点，它的梯度用来计算a的梯度，计算完a梯度后被释放
c.grad is None


True

#### 查看手动求导与自动求导的区别

In [11]:
def f(x):
    y = x ** 2 * t.exp(x)
    return y
def gradf(x):
    '''手动求导'''
    dx = 2*x*t.exp(x) + x ** 2 * t.exp(x)
    return dx


In [12]:
x = V(t.randn(3,4),requires_grad = True)
y = f(x)
y


tensor([[1.2257e-01, 7.1639e+00, 3.5866e-01, 6.9493e-04],
        [3.9960e-02, 4.3949e-01, 2.2098e-02, 3.4179e-02],
        [8.4449e-02, 4.6632e-01, 2.9621e-01, 1.8807e-01]],
       grad_fn=<MulBackward0>)

In [13]:
#自动求导
y.backward(t.ones(y.size()))
x.grad


tensor([[ 0.9365, 17.7176, -0.3769, -0.0513],
        [ 0.4780, -0.2808, -0.2522,  0.4367],
        [ 0.7449, -0.2383, -0.4261, -0.4611]])

In [14]:
#手动求导
gradf(x)

tensor([[ 0.9365, 17.7176, -0.3769, -0.0513],
        [ 0.4780, -0.2808, -0.2522,  0.4367],
        [ 0.7449, -0.2383, -0.4261, -0.4611]], grad_fn=<AddBackward0>)